let productName: string = "Laptop";
let message: string = 'Hello World';
let price: number = 999.99;
let quantity: number = 5;
let isInStock: boolean = true;
let isOnSale: boolean = false;
let emptyValue: null = null;
let notAssigned: undefined = undefined;
console.log(productName);
console.log(message);
console.log(price);
console.log(quantity);
console.log(isInStock);
console.log(emptyValue);